// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMNscdrXt6tt-79DNBB6Cv1Z2nrmr57Qg',
    appId: '1:498071855638:web:1c52418e92f07426390b37',
    messagingSenderId: '498071855638',
    projectId: 'campus-info-share',
    authDomain: 'campus-info-share.firebaseapp.com',
    storageBucket: 'campus-info-share.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRredqDSeMKWbsMX03XAxFpTi8w8fLmyw',
    appId: '1:498071855638:android:67e6d77ebf4a8d26390b37',
    messagingSenderId: '498071855638',
    projectId: 'campus-info-share',
    storageBucket: 'campus-info-share.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMNscdrXt6tt-79DNBB6Cv1Z2nrmr57Qg',
    appId: '1:498071855638:web:6ac7b045f9fa4416390b37',
    messagingSenderId: '498071855638',
    projectId: 'campus-info-share',
    authDomain: 'campus-info-share.firebaseapp.com',
    storageBucket: 'campus-info-share.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmykaWgase8-cMBgFfWpyZZnAroC2Zk6w',
    appId: '1:498071855638:ios:2148f8b51329ad67390b37',
    messagingSenderId: '498071855638',
    projectId: 'campus-info-share',
    storageBucket: 'campus-info-share.firebasestorage.app',
    iosBundleId: 'com.example.studentInformation1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmykaWgase8-cMBgFfWpyZZnAroC2Zk6w',
    appId: '1:498071855638:ios:2148f8b51329ad67390b37',
    messagingSenderId: '498071855638',
    projectId: 'campus-info-share',
    storageBucket: 'campus-info-share.firebasestorage.app',
    iosBundleId: 'com.example.studentInformation1',
  );
}
